
CREATE TABLE inventories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    location VARCHAR(100),
    price BIGINT
);

INSERT INTO inventories (name, location, price) VALUES ('TS V-15', 'ბათუმი', 249198);
INSERT INTO inventories (name, location, price) VALUES ('JS V-91', 'თბილისი', 247655);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-23', 'ბათუმი', 101662);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-77', 'რუსთავი', 133069);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-59', 'თბილისი', 20104);
INSERT INTO inventories (name, location, price) VALUES ('JS V-44', 'გორი', 221421);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-28', 'ხაშური', 110329);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-54', 'თბილისი', 286079);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-43', 'თბილისი', 117791);
INSERT INTO inventories (name, location, price) VALUES ('JS V-95', 'თბილისი', 240841);
INSERT INTO inventories (name, location, price) VALUES ('TS V-21', 'რუსთავი', 103311);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-47', 'ზუგდიდი', 95444);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-23', 'გორი', 256205);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-84', 'ქუთაისი', 13359);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-82', 'ქუთაისი', 135573);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-86', 'გორი', 196350);
INSERT INTO inventories (name, location, price) VALUES ('JS V-57', 'ზუგდიდი', 62999);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-87', 'რუსთავი', 26413);
INSERT INTO inventories (name, location, price) VALUES ('JS V-45', 'ბათუმი', 115068);
INSERT INTO inventories (name, location, price) VALUES ('TS V-33', 'გორი', 223485);
INSERT INTO inventories (name, location, price) VALUES ('JS V-52', 'ზუგდიდი', 298819);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-48', 'ხაშური', 149418);
INSERT INTO inventories (name, location, price) VALUES ('JS V-58', 'ხაშური', 58567);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-67', 'ბათუმი', 40534);
INSERT INTO inventories (name, location, price) VALUES ('TS V-19', 'რუსთავი', 253181);
INSERT INTO inventories (name, location, price) VALUES ('TS V-49', 'ზუგდიდი', 43956);
INSERT INTO inventories (name, location, price) VALUES ('JS V-87', 'რუსთავი', 275120);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-55', 'გორი', 84710);
INSERT INTO inventories (name, location, price) VALUES ('JS V-55', 'თბილისი', 203851);
INSERT INTO inventories (name, location, price) VALUES ('JS V-64', 'თბილისი', 74907);
INSERT INTO inventories (name, location, price) VALUES ('JS V-13', 'გორი', 178483);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-70', 'ქუთაისი', 30746);
INSERT INTO inventories (name, location, price) VALUES ('JS V-59', 'ქუთაისი', 168183);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-68', 'ქუთაისი', 206418);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-50', 'ხაშური', 139437);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-45', 'თბილისი', 28938);
INSERT INTO inventories (name, location, price) VALUES ('TS V-86', 'თბილისი', 283787);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-26', 'გორი', 201403);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-80', 'ქუთაისი', 9506);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-15', 'გორი', 200215);
INSERT INTO inventories (name, location, price) VALUES ('TS V-67', 'გორი', 84195);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-49', 'გორი', 109603);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-55', 'გორი', 88692);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-16', 'ხაშური', 21870);
INSERT INTO inventories (name, location, price) VALUES ('JS V-51', 'ქუთაისი', 272671);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-19', 'ხაშური', 112681);
INSERT INTO inventories (name, location, price) VALUES ('JS V-69', 'რუსთავი', 173757);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-84', 'გორი', 288148);
INSERT INTO inventories (name, location, price) VALUES ('JS V-93', 'რუსთავი', 22060);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-89', 'რუსთავი', 93224);
INSERT INTO inventories (name, location, price) VALUES ('JS V-57', 'რუსთავი', 109422);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-87', 'ბათუმი', 104041);
INSERT INTO inventories (name, location, price) VALUES ('JS V-68', 'ზუგდიდი', 29849);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-70', 'გორი', 214750);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-22', 'რუსთავი', 291689);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-57', 'ზუგდიდი', 119480);
INSERT INTO inventories (name, location, price) VALUES ('JS V-20', 'ქუთაისი', 70432);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-42', 'რუსთავი', 22592);
INSERT INTO inventories (name, location, price) VALUES ('JS V-29', 'ქუთაისი', 88677);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-81', 'გორი', 168469);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-28', 'ზუგდიდი', 117644);
INSERT INTO inventories (name, location, price) VALUES ('JS V-57', 'თბილისი', 238078);
INSERT INTO inventories (name, location, price) VALUES ('JS V-39', 'თბილისი', 256999);
INSERT INTO inventories (name, location, price) VALUES ('JS V-11', 'ქუთაისი', 154898);
INSERT INTO inventories (name, location, price) VALUES ('TS V-51', 'ხაშური', 113374);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-84', 'რუსთავი', 54076);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-74', 'ბათუმი', 92456);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-62', 'ხაშური', 130611);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-77', 'თბილისი', 134461);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-80', 'ზუგდიდი', 137732);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-36', 'ზუგდიდი', 42799);
INSERT INTO inventories (name, location, price) VALUES ('TS V-91', 'ხაშური', 51886);
INSERT INTO inventories (name, location, price) VALUES ('TS V-33', 'ხაშური', 113946);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-52', 'ბათუმი', 205491);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-88', 'თბილისი', 253418);
INSERT INTO inventories (name, location, price) VALUES ('JS V-38', 'ქუთაისი', 6920);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-74', 'ბათუმი', 8610);
INSERT INTO inventories (name, location, price) VALUES ('JS V-80', 'ზუგდიდი', 142133);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-26', 'ქუთაისი', 77770);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-29', 'გორი', 167613);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-78', 'ხაშური', 222782);
INSERT INTO inventories (name, location, price) VALUES ('TS V-61', 'ქუთაისი', 99605);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-91', 'ბათუმი', 6530);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-14', 'ქუთაისი', 241135);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-76', 'ბათუმი', 16990);
INSERT INTO inventories (name, location, price) VALUES ('TS V-36', 'რუსთავი', 142746);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-93', 'ზუგდიდი', 223375);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-35', 'ქუთაისი', 277439);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-69', 'ხაშური', 80429);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-56', 'თბილისი', 272611);
INSERT INTO inventories (name, location, price) VALUES ('JS V-87', 'გორი', 262337);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-15', 'ხაშური', 2586);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-18', 'თბილისი', 79014);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-27', 'თბილისი', 267145);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-98', 'ხაშური', 189116);
INSERT INTO inventories (name, location, price) VALUES ('TS V-15', 'ბათუმი', 100740);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-96', 'რუსთავი', 257470);
INSERT INTO inventories (name, location, price) VALUES ('TS V-66', 'ზუგდიდი', 252787);
INSERT INTO inventories (name, location, price) VALUES ('JS V-57', 'თბილისი', 241145);
INSERT INTO inventories (name, location, price) VALUES ('TS V-62', 'ქუთაისი', 208505);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-66', 'ქუთაისი', 207374);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-57', 'რუსთავი', 88167);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-70', 'თბილისი', 274300);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-93', 'თბილისი', 168003);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-10', 'ზუგდიდი', 286034);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-94', 'ქუთაისი', 211728);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-18', 'ხაშური', 198074);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-25', 'ხაშური', 8209);
INSERT INTO inventories (name, location, price) VALUES ('TS V-85', 'რუსთავი', 44556);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-98', 'რუსთავი', 183117);
INSERT INTO inventories (name, location, price) VALUES ('JS V-49', 'ბათუმი', 57795);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-68', 'თბილისი', 65584);
INSERT INTO inventories (name, location, price) VALUES ('JS V-43', 'თბილისი', 189235);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-71', 'გორი', 21787);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-82', 'რუსთავი', 222446);
INSERT INTO inventories (name, location, price) VALUES ('TS V-49', 'რუსთავი', 205273);
INSERT INTO inventories (name, location, price) VALUES ('TS V-68', 'გორი', 107824);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-87', 'ხაშური', 41949);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-58', 'გორი', 45225);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-60', 'ზუგდიდი', 284721);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-34', 'გორი', 73805);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-83', 'ქუთაისი', 219241);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-75', 'ქუთაისი', 181004);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-41', 'ქუთაისი', 287593);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-70', 'ზუგდიდი', 191934);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-52', 'ხაშური', 206537);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-98', 'თბილისი', 253306);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-91', 'ხაშური', 188421);
INSERT INTO inventories (name, location, price) VALUES ('JS V-19', 'რუსთავი', 120993);
INSERT INTO inventories (name, location, price) VALUES ('JS V-15', 'ქუთაისი', 53235);
INSERT INTO inventories (name, location, price) VALUES ('TS V-93', 'ხაშური', 172770);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-49', 'ქუთაისი', 296334);
INSERT INTO inventories (name, location, price) VALUES ('JS V-74', 'ბათუმი', 114288);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-26', 'ბათუმი', 209802);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-29', 'თბილისი', 30016);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-28', 'გორი', 45470);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-69', 'ზუგდიდი', 60736);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-83', 'რუსთავი', 270995);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-45', 'ქუთაისი', 250319);
INSERT INTO inventories (name, location, price) VALUES ('TS V-65', 'ბათუმი', 164363);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-61', 'თბილისი', 138088);
INSERT INTO inventories (name, location, price) VALUES ('JS V-18', 'რუსთავი', 127628);
INSERT INTO inventories (name, location, price) VALUES ('TS V-39', 'გორი', 186215);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-26', 'თბილისი', 249500);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-51', 'თბილისი', 74738);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-20', 'ბათუმი', 201855);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-77', 'თბილისი', 101858);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-24', 'ქუთაისი', 122344);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-91', 'ბათუმი', 172774);
INSERT INTO inventories (name, location, price) VALUES ('TS V-64', 'თბილისი', 106589);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-23', 'თბილისი', 152550);
INSERT INTO inventories (name, location, price) VALUES ('JS V-35', 'თბილისი', 167218);
INSERT INTO inventories (name, location, price) VALUES ('TS V-45', 'ზუგდიდი', 196528);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-69', 'რუსთავი', 2666);
INSERT INTO inventories (name, location, price) VALUES ('JS V-16', 'გორი', 122943);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-94', 'გორი', 274176);
INSERT INTO inventories (name, location, price) VALUES ('TS V-24', 'რუსთავი', 105659);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-69', 'ბათუმი', 156288);
INSERT INTO inventories (name, location, price) VALUES ('JS V-66', 'რუსთავი', 13979);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-76', 'რუსთავი', 272641);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-89', 'ხაშური', 87005);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-14', 'ქუთაისი', 176790);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-12', 'რუსთავი', 7227);
INSERT INTO inventories (name, location, price) VALUES ('TS V-10', 'ბათუმი', 122841);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-60', 'ბათუმი', 9951);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-43', 'ხაშური', 246923);
INSERT INTO inventories (name, location, price) VALUES ('JS V-98', 'ზუგდიდი', 271026);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-34', 'თბილისი', 18821);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-28', 'ბათუმი', 28575);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-74', 'ხაშური', 126998);
INSERT INTO inventories (name, location, price) VALUES ('JS V-59', 'ზუგდიდი', 188287);
INSERT INTO inventories (name, location, price) VALUES ('TS V-22', 'ბათუმი', 197640);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-54', 'თბილისი', 190575);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-34', 'რუსთავი', 269555);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-77', 'რუსთავი', 278993);
INSERT INTO inventories (name, location, price) VALUES ('JS V-38', 'გორი', 202633);
INSERT INTO inventories (name, location, price) VALUES ('JS V-82', 'ბათუმი', 68595);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-91', 'ხაშური', 10497);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-97', 'ხაშური', 115946);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-14', 'რუსთავი', 224303);
INSERT INTO inventories (name, location, price) VALUES ('TS V-95', 'ბათუმი', 272472);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-40', 'თბილისი', 121414);
INSERT INTO inventories (name, location, price) VALUES ('JS V-31', 'ხაშური', 259343);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-68', 'რუსთავი', 174726);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-89', 'თბილისი', 38983);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-78', 'ბათუმი', 117338);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-62', 'გორი', 4143);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-64', 'ბათუმი', 207755);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-89', 'ხაშური', 48700);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-77', 'ხაშური', 98627);
INSERT INTO inventories (name, location, price) VALUES ('TS V-39', 'ბათუმი', 296066);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-99', 'ბათუმი', 119919);
INSERT INTO inventories (name, location, price) VALUES ('TS V-41', 'თბილისი', 45909);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-12', 'რუსთავი', 198432);
INSERT INTO inventories (name, location, price) VALUES ('TS V-90', 'თბილისი', 86498);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-74', 'ქუთაისი', 161297);
INSERT INTO inventories (name, location, price) VALUES ('TS V-27', 'ბათუმი', 159770);
INSERT INTO inventories (name, location, price) VALUES ('JS V-54', 'თბილისი', 20180);
INSERT INTO inventories (name, location, price) VALUES ('JS V-59', 'ზუგდიდი', 297795);
INSERT INTO inventories (name, location, price) VALUES ('TS V-26', 'ქუთაისი', 99798);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-65', 'ხაშური', 76887);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-42', 'ბათუმი', 121472);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-66', 'ხაშური', 59418);
INSERT INTO inventories (name, location, price) VALUES ('JS V-15', 'რუსთავი', 255462);
INSERT INTO inventories (name, location, price) VALUES ('TS V-34', 'ქუთაისი', 174973);
INSERT INTO inventories (name, location, price) VALUES ('TS V-35', 'ხაშური', 97760);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-41', 'გორი', 13556);
INSERT INTO inventories (name, location, price) VALUES ('TS V-24', 'ქუთაისი', 105645);
INSERT INTO inventories (name, location, price) VALUES ('JS V-56', 'თბილისი', 175135);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-98', 'ბათუმი', 21107);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-32', 'თბილისი', 262526);
INSERT INTO inventories (name, location, price) VALUES ('JS V-82', 'ხაშური', 283469);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-15', 'ხაშური', 89742);
INSERT INTO inventories (name, location, price) VALUES ('JS V-74', 'თბილისი', 249704);
INSERT INTO inventories (name, location, price) VALUES ('JS V-39', 'გორი', 72896);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-29', 'თბილისი', 115843);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-41', 'ბათუმი', 6121);
INSERT INTO inventories (name, location, price) VALUES ('TS V-91', 'თბილისი', 135972);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-71', 'ზუგდიდი', 252744);
INSERT INTO inventories (name, location, price) VALUES ('TS V-25', 'ზუგდიდი', 127681);
INSERT INTO inventories (name, location, price) VALUES ('JS V-58', 'ქუთაისი', 155553);
INSERT INTO inventories (name, location, price) VALUES ('JS V-93', 'ხაშური', 116395);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-95', 'რუსთავი', 68201);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-46', 'რუსთავი', 264370);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-12', 'ქუთაისი', 42695);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-30', 'ქუთაისი', 120708);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-48', 'ზუგდიდი', 259076);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-62', 'ზუგდიდი', 32295);
INSERT INTO inventories (name, location, price) VALUES ('JS V-18', 'ხაშური', 246314);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-50', 'ბათუმი', 40130);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-75', 'რუსთავი', 14752);
INSERT INTO inventories (name, location, price) VALUES ('TS V-33', 'ქუთაისი', 110960);
INSERT INTO inventories (name, location, price) VALUES ('TS V-69', 'ზუგდიდი', 159723);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-85', 'ქუთაისი', 29545);
INSERT INTO inventories (name, location, price) VALUES ('TS V-12', 'გორი', 106515);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-13', 'ქუთაისი', 206136);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-25', 'რუსთავი', 199444);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-22', 'ზუგდიდი', 179532);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-62', 'გორი', 271952);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-94', 'ბათუმი', 181062);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-44', 'ხაშური', 130523);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-85', 'ბათუმი', 78516);
INSERT INTO inventories (name, location, price) VALUES ('JS V-45', 'ზუგდიდი', 54002);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-93', 'გორი', 199014);
INSERT INTO inventories (name, location, price) VALUES ('TS V-90', 'თბილისი', 105609);
INSERT INTO inventories (name, location, price) VALUES ('TS V-41', 'ქუთაისი', 30134);
INSERT INTO inventories (name, location, price) VALUES ('JS V-83', 'ხაშური', 37742);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-35', 'გორი', 78454);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-46', 'გორი', 14167);
INSERT INTO inventories (name, location, price) VALUES ('JS V-50', 'ბათუმი', 184900);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-16', 'ზუგდიდი', 292436);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-67', 'ქუთაისი', 215315);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-33', 'ქუთაისი', 205380);
INSERT INTO inventories (name, location, price) VALUES ('TS V-39', 'თბილისი', 269095);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-97', 'თბილისი', 282559);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-85', 'რუსთავი', 263301);
INSERT INTO inventories (name, location, price) VALUES ('TS V-87', 'ქუთაისი', 234548);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-47', 'რუსთავი', 210654);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-10', 'ხაშური', 9552);
INSERT INTO inventories (name, location, price) VALUES ('JS V-69', 'ხაშური', 257318);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-30', 'გორი', 102657);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-14', 'ზუგდიდი', 196245);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-39', 'თბილისი', 120544);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-88', 'ხაშური', 83561);
INSERT INTO inventories (name, location, price) VALUES ('JS V-88', 'ქუთაისი', 247952);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-89', 'ქუთაისი', 227504);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-85', 'ბათუმი', 184771);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-73', 'ქუთაისი', 142202);
INSERT INTO inventories (name, location, price) VALUES ('JS V-63', 'თბილისი', 290457);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-63', 'თბილისი', 297557);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-67', 'რუსთავი', 112685);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-37', 'გორი', 109534);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-86', 'ზუგდიდი', 170461);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-95', 'ზუგდიდი', 73495);
INSERT INTO inventories (name, location, price) VALUES ('TS V-62', 'ბათუმი', 28347);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-65', 'თბილისი', 290807);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-74', 'გორი', 41845);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-53', 'რუსთავი', 217153);
INSERT INTO inventories (name, location, price) VALUES ('JS V-69', 'ხაშური', 173737);
INSERT INTO inventories (name, location, price) VALUES ('JS V-82', 'გორი', 72995);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-86', 'თბილისი', 123043);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-83', 'თბილისი', 191475);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-42', 'ბათუმი', 95670);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-33', 'თბილისი', 224749);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-93', 'გორი', 176769);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-85', 'ბათუმი', 128486);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-98', 'გორი', 164792);
INSERT INTO inventories (name, location, price) VALUES ('JS V-72', 'თბილისი', 5119);
INSERT INTO inventories (name, location, price) VALUES ('TS V-85', 'ქუთაისი', 137532);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-68', 'თბილისი', 2605);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-39', 'ხაშური', 152206);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-97', 'ქუთაისი', 227731);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-58', 'ქუთაისი', 68192);
INSERT INTO inventories (name, location, price) VALUES ('TS V-97', 'რუსთავი', 294537);
INSERT INTO inventories (name, location, price) VALUES ('TS V-82', 'ქუთაისი', 158238);
INSERT INTO inventories (name, location, price) VALUES ('TS V-15', 'ზუგდიდი', 85794);
INSERT INTO inventories (name, location, price) VALUES ('TS V-24', 'ზუგდიდი', 278459);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-60', 'რუსთავი', 93670);
INSERT INTO inventories (name, location, price) VALUES ('JS V-82', 'თბილისი', 285221);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-29', 'ზუგდიდი', 32209);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-10', 'ბათუმი', 257925);
INSERT INTO inventories (name, location, price) VALUES ('JS V-89', 'გორი', 281057);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-82', 'ქუთაისი', 174418);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-71', 'ბათუმი', 29272);
INSERT INTO inventories (name, location, price) VALUES ('JS V-38', 'ზუგდიდი', 169616);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-91', 'ქუთაისი', 289143);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-77', 'ქუთაისი', 174845);
INSERT INTO inventories (name, location, price) VALUES ('TS V-72', 'ხაშური', 167704);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-89', 'ქუთაისი', 279611);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-34', 'თბილისი', 262983);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-83', 'გორი', 129362);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-85', 'ხაშური', 93270);
INSERT INTO inventories (name, location, price) VALUES ('JS V-85', 'ხაშური', 164229);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-62', 'ქუთაისი', 286247);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-69', 'გორი', 170224);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-99', 'ზუგდიდი', 297524);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-60', 'გორი', 145085);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-18', 'ზუგდიდი', 274428);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-93', 'ქუთაისი', 287249);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-13', 'რუსთავი', 75904);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-26', 'ზუგდიდი', 30262);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-52', 'ბათუმი', 224617);
INSERT INTO inventories (name, location, price) VALUES ('JS V-97', 'ხაშური', 99781);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-95', 'ქუთაისი', 251713);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-51', 'რუსთავი', 283255);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-33', 'ბათუმი', 208186);
INSERT INTO inventories (name, location, price) VALUES ('TS V-22', 'ხაშური', 55737);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-52', 'თბილისი', 81410);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-63', 'ბათუმი', 179641);
INSERT INTO inventories (name, location, price) VALUES ('JS V-39', 'ქუთაისი', 60401);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-63', 'ქუთაისი', 199271);
INSERT INTO inventories (name, location, price) VALUES ('JS V-96', 'ზუგდიდი', 111617);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-46', 'ხაშური', 226856);
INSERT INTO inventories (name, location, price) VALUES ('TS V-93', 'ქუთაისი', 238604);
INSERT INTO inventories (name, location, price) VALUES ('JS V-99', 'გორი', 275718);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-84', 'თბილისი', 140223);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-68', 'ხაშური', 288391);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-98', 'ხაშური', 159647);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-99', 'გორი', 101961);
INSERT INTO inventories (name, location, price) VALUES ('JS V-71', 'ქუთაისი', 220424);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-10', 'ბათუმი', 30226);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-45', 'ქუთაისი', 12019);
INSERT INTO inventories (name, location, price) VALUES ('TS V-80', 'თბილისი', 236589);
INSERT INTO inventories (name, location, price) VALUES ('JS V-85', 'რუსთავი', 22241);
INSERT INTO inventories (name, location, price) VALUES ('JS V-37', 'თბილისი', 286372);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-11', 'თბილისი', 27406);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-83', 'ბათუმი', 85407);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-79', 'ქუთაისი', 280768);
INSERT INTO inventories (name, location, price) VALUES ('TS V-64', 'ხაშური', 252570);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-54', 'ზუგდიდი', 16645);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-72', 'ქუთაისი', 294768);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-15', 'ქუთაისი', 121413);
INSERT INTO inventories (name, location, price) VALUES ('TS V-56', 'ზუგდიდი', 64167);
INSERT INTO inventories (name, location, price) VALUES ('JS V-12', 'რუსთავი', 153598);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-66', 'ბათუმი', 255042);
INSERT INTO inventories (name, location, price) VALUES ('TS V-80', 'გორი', 152634);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-20', 'ზუგდიდი', 209421);
INSERT INTO inventories (name, location, price) VALUES ('JS V-42', 'ხაშური', 207486);
INSERT INTO inventories (name, location, price) VALUES ('JS V-70', 'გორი', 233157);
INSERT INTO inventories (name, location, price) VALUES ('JS V-79', 'თბილისი', 279994);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-13', 'რუსთავი', 187769);
INSERT INTO inventories (name, location, price) VALUES ('TS V-79', 'რუსთავი', 276496);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-41', 'რუსთავი', 166471);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-98', 'რუსთავი', 38188);
INSERT INTO inventories (name, location, price) VALUES ('JS V-73', 'ხაშური', 236679);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-92', 'თბილისი', 185114);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-91', 'ბათუმი', 299001);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-86', 'თბილისი', 90230);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-91', 'თბილისი', 256086);
INSERT INTO inventories (name, location, price) VALUES ('TS V-79', 'ბათუმი', 207873);
INSERT INTO inventories (name, location, price) VALUES ('TS V-40', 'ბათუმი', 91477);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-71', 'ბათუმი', 170675);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-52', 'თბილისი', 37561);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-89', 'რუსთავი', 285874);
INSERT INTO inventories (name, location, price) VALUES ('JS V-18', 'რუსთავი', 57391);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-92', 'ქუთაისი', 241914);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-73', 'ბათუმი', 248780);
INSERT INTO inventories (name, location, price) VALUES ('JS V-91', 'რუსთავი', 5187);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-67', 'რუსთავი', 61072);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-17', 'გორი', 30380);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-50', 'რუსთავი', 18630);
INSERT INTO inventories (name, location, price) VALUES ('JS V-41', 'თბილისი', 159897);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-42', 'რუსთავი', 258089);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-71', 'თბილისი', 171500);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-51', 'ხაშური', 237521);
INSERT INTO inventories (name, location, price) VALUES ('TS V-26', 'თბილისი', 296434);
INSERT INTO inventories (name, location, price) VALUES ('JS V-12', 'ბათუმი', 86917);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-68', 'ზუგდიდი', 147688);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-37', 'ზუგდიდი', 179247);
INSERT INTO inventories (name, location, price) VALUES ('TS V-59', 'ბათუმი', 54556);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-55', 'ქუთაისი', 225818);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-43', 'რუსთავი', 66783);
INSERT INTO inventories (name, location, price) VALUES ('JS V-31', 'ბათუმი', 238185);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-61', 'თბილისი', 239806);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-49', 'ბათუმი', 62296);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-50', 'თბილისი', 266254);
INSERT INTO inventories (name, location, price) VALUES ('TS V-15', 'გორი', 150181);
INSERT INTO inventories (name, location, price) VALUES ('TS V-84', 'ხაშური', 58826);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-38', 'თბილისი', 162731);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-46', 'ზუგდიდი', 294652);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-30', 'ქუთაისი', 51864);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-20', 'ხაშური', 83496);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-46', 'ქუთაისი', 255445);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-29', 'ქუთაისი', 6816);
INSERT INTO inventories (name, location, price) VALUES ('JS V-96', 'ზუგდიდი', 163635);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-75', 'ბათუმი', 17708);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-41', 'რუსთავი', 239566);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-67', 'ქუთაისი', 49808);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-65', 'ზუგდიდი', 87559);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-90', 'თბილისი', 225219);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-39', 'გორი', 174494);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-63', 'ქუთაისი', 19422);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-34', 'თბილისი', 238845);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-67', 'ხაშური', 266615);
INSERT INTO inventories (name, location, price) VALUES ('TS V-72', 'ხაშური', 260355);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-62', 'ხაშური', 196689);
INSERT INTO inventories (name, location, price) VALUES ('TS V-38', 'რუსთავი', 184497);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-23', 'ზუგდიდი', 256109);
INSERT INTO inventories (name, location, price) VALUES ('JS V-43', 'ბათუმი', 124336);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-87', 'რუსთავი', 254930);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-34', 'ქუთაისი', 18161);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-81', 'თბილისი', 245132);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-55', 'ზუგდიდი', 262868);
INSERT INTO inventories (name, location, price) VALUES ('TS V-96', 'გორი', 3538);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-93', 'რუსთავი', 11353);
INSERT INTO inventories (name, location, price) VALUES ('JS V-45', 'გორი', 57350);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-89', 'ზუგდიდი', 147142);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-85', 'ქუთაისი', 86414);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-45', 'თბილისი', 56614);
INSERT INTO inventories (name, location, price) VALUES ('TS V-33', 'რუსთავი', 77758);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-69', 'გორი', 94806);
INSERT INTO inventories (name, location, price) VALUES ('TS V-95', 'ზუგდიდი', 288671);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-61', 'თბილისი', 117032);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-71', 'გორი', 69584);
INSERT INTO inventories (name, location, price) VALUES ('TS V-34', 'თბილისი', 232162);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-79', 'ბათუმი', 194680);
INSERT INTO inventories (name, location, price) VALUES ('JS V-41', 'გორი', 261745);
INSERT INTO inventories (name, location, price) VALUES ('JS V-12', 'ბათუმი', 37886);
INSERT INTO inventories (name, location, price) VALUES ('TS V-70', 'თბილისი', 24894);
INSERT INTO inventories (name, location, price) VALUES ('JS V-66', 'ქუთაისი', 139979);
INSERT INTO inventories (name, location, price) VALUES ('TS V-77', 'ბათუმი', 264824);
INSERT INTO inventories (name, location, price) VALUES ('TS V-17', 'ხაშური', 201697);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-91', 'რუსთავი', 129270);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-62', 'რუსთავი', 151078);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-22', 'რუსთავი', 163754);
INSERT INTO inventories (name, location, price) VALUES ('TS V-99', 'ხაშური', 71662);
INSERT INTO inventories (name, location, price) VALUES ('TS V-19', 'ზუგდიდი', 44833);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-13', 'გორი', 226473);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-26', 'ხაშური', 2308);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-24', 'თბილისი', 101761);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-25', 'გორი', 98861);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-67', 'ბათუმი', 73304);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-61', 'თბილისი', 1085);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-41', 'ხაშური', 188125);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-26', 'ზუგდიდი', 295104);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-49', 'ქუთაისი', 226570);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-41', 'რუსთავი', 277533);
INSERT INTO inventories (name, location, price) VALUES ('JS V-25', 'ბათუმი', 61145);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-97', 'ზუგდიდი', 265124);
INSERT INTO inventories (name, location, price) VALUES ('TS V-83', 'ზუგდიდი', 61994);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-86', 'რუსთავი', 278187);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-49', 'რუსთავი', 76042);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-76', 'თბილისი', 219132);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-56', 'ზუგდიდი', 243242);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-33', 'ხაშური', 123702);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-13', 'ხაშური', 236398);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-84', 'ხაშური', 233348);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-50', 'რუსთავი', 34018);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-42', 'ქუთაისი', 237572);
INSERT INTO inventories (name, location, price) VALUES ('TS V-77', 'ხაშური', 238535);
INSERT INTO inventories (name, location, price) VALUES ('JS V-55', 'ხაშური', 20062);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-75', 'ქუთაისი', 246978);
INSERT INTO inventories (name, location, price) VALUES ('TS V-76', 'თბილისი', 213408);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-40', 'ხაშური', 199768);
INSERT INTO inventories (name, location, price) VALUES ('TS V-83', 'თბილისი', 35696);
INSERT INTO inventories (name, location, price) VALUES ('TS V-77', 'თბილისი', 41763);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-53', 'რუსთავი', 32526);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-83', 'ქუთაისი', 209991);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-57', 'ქუთაისი', 30703);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-27', 'ბათუმი', 62917);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-78', 'გორი', 4422);
INSERT INTO inventories (name, location, price) VALUES ('JS V-42', 'ხაშური', 213346);
INSERT INTO inventories (name, location, price) VALUES ('TS V-42', 'ზუგდიდი', 85457);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-53', 'გორი', 1060);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-35', 'ზუგდიდი', 37151);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-57', 'რუსთავი', 152789);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-18', 'ქუთაისი', 259906);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-49', 'რუსთავი', 226718);
INSERT INTO inventories (name, location, price) VALUES ('JS V-79', 'ზუგდიდი', 6785);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-36', 'თბილისი', 80916);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-88', 'რუსთავი', 250017);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-64', 'ხაშური', 73566);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-66', 'ხაშური', 74287);
INSERT INTO inventories (name, location, price) VALUES ('TS V-53', 'რუსთავი', 75415);
INSERT INTO inventories (name, location, price) VALUES ('TS V-42', 'რუსთავი', 266256);
INSERT INTO inventories (name, location, price) VALUES ('TS V-20', 'ქუთაისი', 174585);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-90', 'რუსთავი', 161480);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-72', 'გორი', 167721);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-23', 'ბათუმი', 249389);
INSERT INTO inventories (name, location, price) VALUES ('JS V-47', 'ზუგდიდი', 156470);
INSERT INTO inventories (name, location, price) VALUES ('TS V-68', 'თბილისი', 37962);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-29', 'ბათუმი', 193742);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-94', 'ზუგდიდი', 155564);
INSERT INTO inventories (name, location, price) VALUES ('TS V-44', 'ხაშური', 49674);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-15', 'ზუგდიდი', 72469);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-38', 'ხაშური', 185967);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-60', 'ხაშური', 25732);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-16', 'ბათუმი', 102884);
INSERT INTO inventories (name, location, price) VALUES ('JS V-14', 'ზუგდიდი', 190171);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-14', 'ბათუმი', 266085);
INSERT INTO inventories (name, location, price) VALUES ('TS V-89', 'გორი', 95238);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-14', 'გორი', 213716);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-33', 'რუსთავი', 259328);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-46', 'ხაშური', 90282);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-96', 'ზუგდიდი', 202097);
INSERT INTO inventories (name, location, price) VALUES ('JS V-52', 'ხაშური', 86004);
INSERT INTO inventories (name, location, price) VALUES ('JS V-86', 'ქუთაისი', 193765);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-27', 'ბათუმი', 97026);
INSERT INTO inventories (name, location, price) VALUES ('JS V-62', 'გორი', 222147);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-32', 'ქუთაისი', 182124);
INSERT INTO inventories (name, location, price) VALUES ('JS V-56', 'ბათუმი', 37802);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-60', 'გორი', 18215);
INSERT INTO inventories (name, location, price) VALUES ('TS V-70', 'თბილისი', 21439);
INSERT INTO inventories (name, location, price) VALUES ('TS V-88', 'ქუთაისი', 87455);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-77', 'ქუთაისი', 64533);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-41', 'ხაშური', 217030);
INSERT INTO inventories (name, location, price) VALUES ('TS V-81', 'ქუთაისი', 254825);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-72', 'ხაშური', 29678);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-20', 'ბათუმი', 120975);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-20', 'ქუთაისი', 126794);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-89', 'ზუგდიდი', 188904);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-88', 'ქუთაისი', 43275);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-22', 'თბილისი', 247160);
INSERT INTO inventories (name, location, price) VALUES ('JS V-96', 'რუსთავი', 83911);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-92', 'გორი', 55368);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-77', 'რუსთავი', 1323);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-34', 'ქუთაისი', 150540);
INSERT INTO inventories (name, location, price) VALUES ('TS V-38', 'თბილისი', 153289);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-12', 'ბათუმი', 290777);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-96', 'ხაშური', 74633);
INSERT INTO inventories (name, location, price) VALUES ('TS V-70', 'ზუგდიდი', 34665);
INSERT INTO inventories (name, location, price) VALUES ('JS V-77', 'ზუგდიდი', 156662);
INSERT INTO inventories (name, location, price) VALUES ('JS V-69', 'გორი', 142939);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-12', 'რუსთავი', 121826);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-92', 'ზუგდიდი', 211807);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-52', 'ბათუმი', 272563);
INSERT INTO inventories (name, location, price) VALUES ('TS V-12', 'ზუგდიდი', 205346);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-12', 'გორი', 74937);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-88', 'თბილისი', 107062);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-76', 'გორი', 12651);
INSERT INTO inventories (name, location, price) VALUES ('JS V-91', 'ბათუმი', 222981);
INSERT INTO inventories (name, location, price) VALUES ('TS V-59', 'ხაშური', 222558);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-23', 'რუსთავი', 225664);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-39', 'ზუგდიდი', 247506);
INSERT INTO inventories (name, location, price) VALUES ('TS V-51', 'თბილისი', 224413);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-67', 'თბილისი', 141582);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-26', 'ბათუმი', 88143);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-78', 'ხაშური', 234181);
INSERT INTO inventories (name, location, price) VALUES ('JS V-73', 'ზუგდიდი', 81363);
INSERT INTO inventories (name, location, price) VALUES ('TS V-14', 'რუსთავი', 26093);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-77', 'ბათუმი', 256087);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-14', 'ხაშური', 275283);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-68', 'ბათუმი', 174778);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-90', 'ბათუმი', 102849);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-97', 'რუსთავი', 60109);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-44', 'თბილისი', 24829);
INSERT INTO inventories (name, location, price) VALUES ('JS V-36', 'ხაშური', 173398);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-63', 'რუსთავი', 3594);
INSERT INTO inventories (name, location, price) VALUES ('JS V-35', 'თბილისი', 145268);
INSERT INTO inventories (name, location, price) VALUES ('JS V-64', 'რუსთავი', 58671);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-65', 'ზუგდიდი', 172633);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-63', 'გორი', 226234);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-83', 'ბათუმი', 286822);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-49', 'ბათუმი', 282872);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-37', 'ბათუმი', 250850);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-15', 'ქუთაისი', 256585);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-68', 'გორი', 36085);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-74', 'ხაშური', 204122);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-32', 'ქუთაისი', 248225);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-26', 'თბილისი', 21927);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-31', 'ხაშური', 106569);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-68', 'ბათუმი', 203862);
INSERT INTO inventories (name, location, price) VALUES ('TS V-77', 'რუსთავი', 188396);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-49', 'ხაშური', 285893);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-76', 'ზუგდიდი', 263370);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-82', 'ბათუმი', 262091);
INSERT INTO inventories (name, location, price) VALUES ('TS V-71', 'თბილისი', 26739);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-98', 'თბილისი', 94031);
INSERT INTO inventories (name, location, price) VALUES ('TS V-18', 'რუსთავი', 156190);
INSERT INTO inventories (name, location, price) VALUES ('TS V-37', 'ხაშური', 237176);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-66', 'ზუგდიდი', 199584);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-65', 'ზუგდიდი', 142093);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-60', 'ბათუმი', 37034);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-63', 'ხაშური', 130474);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-72', 'ქუთაისი', 259179);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-80', 'გორი', 155004);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-97', 'თბილისი', 11076);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-66', 'რუსთავი', 15525);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-94', 'ქუთაისი', 252889);
INSERT INTO inventories (name, location, price) VALUES ('TS V-16', 'ბათუმი', 79011);
INSERT INTO inventories (name, location, price) VALUES ('JS V-17', 'ხაშური', 37563);
INSERT INTO inventories (name, location, price) VALUES ('TS V-92', 'გორი', 224418);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-17', 'ქუთაისი', 207019);
INSERT INTO inventories (name, location, price) VALUES ('TS V-37', 'გორი', 51758);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-20', 'ზუგდიდი', 97605);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-14', 'ხაშური', 211203);
INSERT INTO inventories (name, location, price) VALUES ('JS V-78', 'ზუგდიდი', 74252);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-37', 'გორი', 116449);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-40', 'რუსთავი', 127735);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-88', 'ქუთაისი', 197256);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-69', 'ბათუმი', 111215);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-74', 'ბათუმი', 125928);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-74', 'ქუთაისი', 89059);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-85', 'რუსთავი', 289460);
INSERT INTO inventories (name, location, price) VALUES ('JS V-72', 'ბათუმი', 6022);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-54', 'გორი', 276876);
INSERT INTO inventories (name, location, price) VALUES ('TS V-63', 'გორი', 127822);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-15', 'ბათუმი', 197652);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-59', 'ზუგდიდი', 247153);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-73', 'ქუთაისი', 134538);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-35', 'გორი', 57646);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-29', 'ბათუმი', 4391);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-69', 'რუსთავი', 221690);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-60', 'გორი', 176199);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-73', 'გორი', 292110);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-45', 'რუსთავი', 22125);
INSERT INTO inventories (name, location, price) VALUES ('TS V-37', 'ბათუმი', 16871);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-35', 'ზუგდიდი', 273565);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-77', 'ბათუმი', 88022);
INSERT INTO inventories (name, location, price) VALUES ('JS V-88', 'რუსთავი', 245813);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-29', 'ქუთაისი', 142924);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-31', 'თბილისი', 286233);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-42', 'ბათუმი', 31708);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-99', 'ქუთაისი', 24280);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-34', 'ზუგდიდი', 259772);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-18', 'ქუთაისი', 216545);
INSERT INTO inventories (name, location, price) VALUES ('JS V-61', 'თბილისი', 96952);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-25', 'ხაშური', 204671);
INSERT INTO inventories (name, location, price) VALUES ('JS V-29', 'ზუგდიდი', 8875);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-28', 'თბილისი', 51022);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-46', 'თბილისი', 125454);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-11', 'ზუგდიდი', 230283);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-58', 'გორი', 191343);
INSERT INTO inventories (name, location, price) VALUES ('TS V-87', 'ზუგდიდი', 204798);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-86', 'ხაშური', 99750);
INSERT INTO inventories (name, location, price) VALUES ('JS V-56', 'ხაშური', 162779);
INSERT INTO inventories (name, location, price) VALUES ('JS V-60', 'ბათუმი', 200005);
INSERT INTO inventories (name, location, price) VALUES ('TS V-22', 'თბილისი', 235271);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-12', 'ბათუმი', 171375);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-47', 'რუსთავი', 147936);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-82', 'ბათუმი', 240053);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-41', 'ზუგდიდი', 194935);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-50', 'ზუგდიდი', 171787);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-85', 'თბილისი', 171564);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-50', 'ქუთაისი', 103606);
INSERT INTO inventories (name, location, price) VALUES ('TS V-65', 'ზუგდიდი', 46995);
INSERT INTO inventories (name, location, price) VALUES ('TS V-30', 'გორი', 60520);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-51', 'გორი', 250357);
INSERT INTO inventories (name, location, price) VALUES ('TS V-98', 'გორი', 260642);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-45', 'თბილისი', 64476);
INSERT INTO inventories (name, location, price) VALUES ('JS V-67', 'გორი', 117012);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-25', 'ქუთაისი', 286869);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-92', 'ქუთაისი', 250256);
INSERT INTO inventories (name, location, price) VALUES ('TS V-76', 'ხაშური', 224243);
INSERT INTO inventories (name, location, price) VALUES ('JS V-59', 'გორი', 168105);
INSERT INTO inventories (name, location, price) VALUES ('JS V-16', 'გორი', 152844);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-93', 'თბილისი', 231630);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-86', 'გორი', 281401);
INSERT INTO inventories (name, location, price) VALUES ('TS V-27', 'ზუგდიდი', 253177);
INSERT INTO inventories (name, location, price) VALUES ('TS V-72', 'ზუგდიდი', 157974);
INSERT INTO inventories (name, location, price) VALUES ('TS V-51', 'ქუთაისი', 136721);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-12', 'ბათუმი', 72141);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-17', 'გორი', 161986);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-46', 'ხაშური', 188450);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-72', 'ბათუმი', 101737);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-10', 'ხაშური', 131393);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-96', 'თბილისი', 244554);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-48', 'ხაშური', 159584);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-43', 'რუსთავი', 248090);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-38', 'რუსთავი', 145999);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-65', 'ქუთაისი', 117284);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-40', 'თბილისი', 82583);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-56', 'გორი', 294961);
INSERT INTO inventories (name, location, price) VALUES ('TS V-55', 'ზუგდიდი', 199708);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-75', 'თბილისი', 225999);
INSERT INTO inventories (name, location, price) VALUES ('TS V-64', 'გორი', 149930);
INSERT INTO inventories (name, location, price) VALUES ('TS V-51', 'თბილისი', 161071);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-72', 'თბილისი', 246724);
INSERT INTO inventories (name, location, price) VALUES ('JS V-88', 'ბათუმი', 287309);
INSERT INTO inventories (name, location, price) VALUES ('TS V-37', 'ხაშური', 254057);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-13', 'თბილისი', 64462);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-91', 'ქუთაისი', 256873);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-21', 'ხაშური', 227978);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-38', 'ხაშური', 83595);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-28', 'ბათუმი', 112269);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-74', 'ქუთაისი', 143154);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-97', 'ხაშური', 136162);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-19', 'ზუგდიდი', 171975);
INSERT INTO inventories (name, location, price) VALUES ('TS V-62', 'ხაშური', 78483);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-43', 'ბათუმი', 46559);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-78', 'თბილისი', 142566);
INSERT INTO inventories (name, location, price) VALUES ('TS V-50', 'ქუთაისი', 81988);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-68', 'რუსთავი', 42860);
INSERT INTO inventories (name, location, price) VALUES ('JS V-42', 'რუსთავი', 105577);
INSERT INTO inventories (name, location, price) VALUES ('JS V-36', 'თბილისი', 141995);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-55', 'ბათუმი', 88662);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-55', 'ზუგდიდი', 243339);
INSERT INTO inventories (name, location, price) VALUES ('TS V-56', 'ხაშური', 210140);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-29', 'თბილისი', 206592);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-30', 'ხაშური', 161881);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-87', 'ქუთაისი', 9362);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-37', 'ბათუმი', 11468);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-69', 'ბათუმი', 122889);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-98', 'თბილისი', 70946);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-56', 'ბათუმი', 136759);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-25', 'რუსთავი', 164494);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-61', 'თბილისი', 47615);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-75', 'ხაშური', 82414);
INSERT INTO inventories (name, location, price) VALUES ('JS V-17', 'თბილისი', 281108);
INSERT INTO inventories (name, location, price) VALUES ('JS V-50', 'ზუგდიდი', 166688);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-13', 'გორი', 283233);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-44', 'ზუგდიდი', 188258);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-62', 'ბათუმი', 142772);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-15', 'ბათუმი', 275765);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-96', 'გორი', 50200);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-58', 'რუსთავი', 252901);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-60', 'ზუგდიდი', 66720);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-58', 'ბათუმი', 173295);
INSERT INTO inventories (name, location, price) VALUES ('TS V-47', 'ბათუმი', 95334);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-64', 'ხაშური', 198299);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-56', 'რუსთავი', 177698);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-12', 'ქუთაისი', 186639);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-14', 'ბათუმი', 38445);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-35', 'ბათუმი', 140289);
INSERT INTO inventories (name, location, price) VALUES ('TS V-97', 'ზუგდიდი', 96676);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-36', 'გორი', 186461);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-63', 'თბილისი', 64472);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-56', 'რუსთავი', 172319);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-91', 'ზუგდიდი', 41033);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-94', 'გორი', 58277);
INSERT INTO inventories (name, location, price) VALUES ('TS V-46', 'თბილისი', 39456);
INSERT INTO inventories (name, location, price) VALUES ('TS V-54', 'თბილისი', 157492);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-62', 'ბათუმი', 209682);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-26', 'ხაშური', 233919);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-99', 'რუსთავი', 207125);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-82', 'გორი', 175463);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-96', 'ხაშური', 115839);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-83', 'რუსთავი', 72993);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-44', 'გორი', 258764);
INSERT INTO inventories (name, location, price) VALUES ('TS V-92', 'თბილისი', 298175);
INSERT INTO inventories (name, location, price) VALUES ('TS V-78', 'ზუგდიდი', 275579);
INSERT INTO inventories (name, location, price) VALUES ('JS V-68', 'ზუგდიდი', 185061);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-29', 'თბილისი', 245772);
INSERT INTO inventories (name, location, price) VALUES ('TS V-36', 'გორი', 156939);
INSERT INTO inventories (name, location, price) VALUES ('TS V-29', 'თბილისი', 271854);
INSERT INTO inventories (name, location, price) VALUES ('TS V-51', 'რუსთავი', 66517);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-50', 'გორი', 73468);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-44', 'გორი', 200157);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-63', 'ხაშური', 284408);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-36', 'რუსთავი', 64665);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-26', 'ბათუმი', 207990);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-56', 'რუსთავი', 130295);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-80', 'რუსთავი', 69659);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-69', 'თბილისი', 162727);
INSERT INTO inventories (name, location, price) VALUES ('JS V-47', 'გორი', 253940);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-50', 'გორი', 95556);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-49', 'ზუგდიდი', 15453);
INSERT INTO inventories (name, location, price) VALUES ('TS V-11', 'თბილისი', 35184);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-97', 'ქუთაისი', 190442);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-76', 'რუსთავი', 17545);
INSERT INTO inventories (name, location, price) VALUES ('TS V-25', 'ქუთაისი', 25417);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-84', 'გორი', 285022);
INSERT INTO inventories (name, location, price) VALUES ('TS V-16', 'ქუთაისი', 174288);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-25', 'ზუგდიდი', 157360);
INSERT INTO inventories (name, location, price) VALUES ('TS V-78', 'რუსთავი', 279995);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-39', 'ხაშური', 112677);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-70', 'ხაშური', 197917);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-17', 'ხაშური', 207629);
INSERT INTO inventories (name, location, price) VALUES ('JS V-19', 'რუსთავი', 249533);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-86', 'თბილისი', 106543);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-89', 'ბათუმი', 244864);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-64', 'ხაშური', 92981);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-89', 'რუსთავი', 262150);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-39', 'გორი', 281778);
INSERT INTO inventories (name, location, price) VALUES ('TS V-77', 'ბათუმი', 122273);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-46', 'ქუთაისი', 99384);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-36', 'რუსთავი', 19932);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-41', 'ბათუმი', 206751);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-87', 'რუსთავი', 98848);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-53', 'ქუთაისი', 209610);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-17', 'ხაშური', 164813);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-21', 'ბათუმი', 199767);
INSERT INTO inventories (name, location, price) VALUES ('TS V-99', 'თბილისი', 48357);
INSERT INTO inventories (name, location, price) VALUES ('JS V-18', 'ზუგდიდი', 112821);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-75', 'ბათუმი', 188929);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-91', 'გორი', 155487);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-80', 'ბათუმი', 235400);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-70', 'ხაშური', 35331);
INSERT INTO inventories (name, location, price) VALUES ('TS V-82', 'ხაშური', 191312);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-31', 'გორი', 233256);
INSERT INTO inventories (name, location, price) VALUES ('JS V-24', 'თბილისი', 223470);
INSERT INTO inventories (name, location, price) VALUES ('TS V-20', 'ზუგდიდი', 76427);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-80', 'გორი', 141147);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-44', 'გორი', 122805);
INSERT INTO inventories (name, location, price) VALUES ('TS V-16', 'ქუთაისი', 170302);
INSERT INTO inventories (name, location, price) VALUES ('TS V-65', 'რუსთავი', 126628);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-88', 'თბილისი', 240468);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-16', 'ბათუმი', 293472);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-64', 'ზუგდიდი', 283216);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-64', 'რუსთავი', 243861);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-10', 'ბათუმი', 220347);
INSERT INTO inventories (name, location, price) VALUES ('TS V-14', 'ქუთაისი', 89130);
INSERT INTO inventories (name, location, price) VALUES ('TS V-76', 'ქუთაისი', 100724);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-56', 'გორი', 95322);
INSERT INTO inventories (name, location, price) VALUES ('TS V-27', 'ბათუმი', 218272);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-92', 'ხაშური', 38881);
INSERT INTO inventories (name, location, price) VALUES ('TS V-62', 'ზუგდიდი', 5009);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-66', 'ქუთაისი', 261129);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-89', 'ბათუმი', 287813);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-31', 'ბათუმი', 12619);
INSERT INTO inventories (name, location, price) VALUES ('TS V-58', 'ბათუმი', 298181);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-96', 'თბილისი', 61907);
INSERT INTO inventories (name, location, price) VALUES ('JS V-55', 'გორი', 270370);
INSERT INTO inventories (name, location, price) VALUES ('TS V-56', 'გორი', 51511);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-43', 'გორი', 151093);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-52', 'ხაშური', 119583);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-82', 'ბათუმი', 57101);
INSERT INTO inventories (name, location, price) VALUES ('TS V-89', 'თბილისი', 3033);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-94', 'გორი', 19122);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-68', 'გორი', 21682);
INSERT INTO inventories (name, location, price) VALUES ('JS V-89', 'გორი', 262337);
INSERT INTO inventories (name, location, price) VALUES ('TS V-47', 'გორი', 89246);
INSERT INTO inventories (name, location, price) VALUES ('JS V-69', 'ხაშური', 210264);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-30', 'თბილისი', 125609);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-16', 'ბათუმი', 221458);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-65', 'თბილისი', 297518);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-59', 'გორი', 288871);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-48', 'ბათუმი', 46281);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-31', 'ქუთაისი', 42493);
INSERT INTO inventories (name, location, price) VALUES ('TS V-97', 'ბათუმი', 155222);
INSERT INTO inventories (name, location, price) VALUES ('JS V-95', 'ქუთაისი', 147024);
INSERT INTO inventories (name, location, price) VALUES ('TS V-85', 'რუსთავი', 173628);
INSERT INTO inventories (name, location, price) VALUES ('TS V-91', 'ქუთაისი', 30326);
INSERT INTO inventories (name, location, price) VALUES ('TS V-85', 'გორი', 152783);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-85', 'ქუთაისი', 147840);
INSERT INTO inventories (name, location, price) VALUES ('TS V-49', 'რუსთავი', 206565);
INSERT INTO inventories (name, location, price) VALUES ('JS V-83', 'გორი', 267825);
INSERT INTO inventories (name, location, price) VALUES ('TS V-28', 'გორი', 32818);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-76', 'თბილისი', 299011);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-28', 'ბათუმი', 135731);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-19', 'ზუგდიდი', 139860);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-18', 'ქუთაისი', 124419);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-37', 'ზუგდიდი', 101633);
INSERT INTO inventories (name, location, price) VALUES ('TS V-47', 'რუსთავი', 141879);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-21', 'ბათუმი', 141274);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-34', 'ხაშური', 259784);
INSERT INTO inventories (name, location, price) VALUES ('JS V-99', 'თბილისი', 92472);
INSERT INTO inventories (name, location, price) VALUES ('TS V-10', 'ხაშური', 290902);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-44', 'ბათუმი', 36143);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-48', 'გორი', 150942);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-15', 'რუსთავი', 74799);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-33', 'ხაშური', 131215);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-56', 'გორი', 93729);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-14', 'ხაშური', 85258);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-41', 'ბათუმი', 113336);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-47', 'რუსთავი', 5245);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-32', 'ბათუმი', 294488);
INSERT INTO inventories (name, location, price) VALUES ('JS V-36', 'თბილისი', 241745);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-28', 'რუსთავი', 11130);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-58', 'ქუთაისი', 198397);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-86', 'ბათუმი', 76650);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-73', 'ქუთაისი', 138499);
INSERT INTO inventories (name, location, price) VALUES ('JS V-69', 'ქუთაისი', 192789);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-65', 'გორი', 68671);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-32', 'თბილისი', 231127);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-24', 'გორი', 71850);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-80', 'თბილისი', 92443);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-51', 'რუსთავი', 77577);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-41', 'ხაშური', 103652);
INSERT INTO inventories (name, location, price) VALUES ('TS V-73', 'თბილისი', 63735);
INSERT INTO inventories (name, location, price) VALUES ('JS V-54', 'ბათუმი', 218877);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-20', 'ბათუმი', 35619);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-80', 'ხაშური', 129206);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-14', 'ბათუმი', 68900);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-98', 'ბათუმი', 259621);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-47', 'თბილისი', 70648);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-59', 'ბათუმი', 67570);
INSERT INTO inventories (name, location, price) VALUES ('TS V-93', 'ქუთაისი', 182708);
INSERT INTO inventories (name, location, price) VALUES ('TS V-61', 'რუსთავი', 289914);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-91', 'ბათუმი', 74054);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-68', 'რუსთავი', 15258);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-77', 'ხაშური', 176480);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-16', 'ზუგდიდი', 244637);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-36', 'რუსთავი', 164417);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-23', 'გორი', 125258);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-27', 'რუსთავი', 169993);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-28', 'ზუგდიდი', 124022);
INSERT INTO inventories (name, location, price) VALUES ('JS V-76', 'თბილისი', 255886);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-89', 'თბილისი', 263483);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-42', 'გორი', 37092);
INSERT INTO inventories (name, location, price) VALUES ('TS V-15', 'ქუთაისი', 136350);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-43', 'რუსთავი', 290978);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-45', 'ბათუმი', 105715);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-92', 'ზუგდიდი', 10798);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-53', 'ზუგდიდი', 241695);
INSERT INTO inventories (name, location, price) VALUES ('JS V-10', 'ქუთაისი', 50547);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-95', 'ზუგდიდი', 271510);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-11', 'რუსთავი', 43073);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-67', 'გორი', 294542);
INSERT INTO inventories (name, location, price) VALUES ('JS V-79', 'ბათუმი', 162464);
INSERT INTO inventories (name, location, price) VALUES ('JS V-85', 'ქუთაისი', 101845);
INSERT INTO inventories (name, location, price) VALUES ('JS V-87', 'ქუთაისი', 250480);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-98', 'ზუგდიდი', 177170);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-34', 'გორი', 54647);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-88', 'ქუთაისი', 1795);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-41', 'ზუგდიდი', 176253);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-49', 'ზუგდიდი', 289670);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-66', 'გორი', 127872);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-99', 'ქუთაისი', 27366);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-97', 'ზუგდიდი', 19006);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-62', 'ხაშური', 151537);
INSERT INTO inventories (name, location, price) VALUES ('JS V-42', 'ბათუმი', 64753);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-27', 'ბათუმი', 217948);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-97', 'გორი', 107564);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-79', 'ზუგდიდი', 299453);
INSERT INTO inventories (name, location, price) VALUES ('JS V-15', 'ხაშური', 138966);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-45', 'თბილისი', 127302);
INSERT INTO inventories (name, location, price) VALUES ('JS V-81', 'ხაშური', 15788);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-86', 'ზუგდიდი', 245823);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-49', 'რუსთავი', 257061);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-14', 'ხაშური', 2087);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-15', 'ზუგდიდი', 87019);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-90', 'ქუთაისი', 77114);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-68', 'თბილისი', 285503);
INSERT INTO inventories (name, location, price) VALUES ('JS V-14', 'გორი', 65472);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-99', 'ქუთაისი', 161345);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-11', 'ზუგდიდი', 37543);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-18', 'რუსთავი', 198945);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-32', 'თბილისი', 251324);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-32', 'თბილისი', 231059);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-45', 'ბათუმი', 91092);
INSERT INTO inventories (name, location, price) VALUES ('TS V-11', 'ხაშური', 39864);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-77', 'ბათუმი', 247491);
INSERT INTO inventories (name, location, price) VALUES ('JS V-91', 'ბათუმი', 70663);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-87', 'ხაშური', 143044);
INSERT INTO inventories (name, location, price) VALUES ('TS V-18', 'ქუთაისი', 297676);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-30', 'რუსთავი', 294275);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-12', 'ხაშური', 17729);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-85', 'გორი', 120932);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-76', 'ხაშური', 42524);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-76', 'ზუგდიდი', 283568);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-62', 'ზუგდიდი', 133684);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-57', 'გორი', 290824);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-93', 'გორი', 279772);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-85', 'რუსთავი', 67332);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-91', 'ზუგდიდი', 152147);
INSERT INTO inventories (name, location, price) VALUES ('JS V-13', 'ქუთაისი', 258930);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-92', 'გორი', 220236);
INSERT INTO inventories (name, location, price) VALUES ('TS V-60', 'გორი', 217776);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-66', 'ზუგდიდი', 49247);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-49', 'თბილისი', 289121);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-13', 'ქუთაისი', 209558);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-54', 'ქუთაისი', 66789);
INSERT INTO inventories (name, location, price) VALUES ('JS V-25', 'თბილისი', 58298);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-40', 'თბილისი', 103702);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-68', 'ქუთაისი', 67995);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-69', 'ქუთაისი', 160326);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-22', 'ქუთაისი', 16518);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-96', 'რუსთავი', 180439);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-30', 'ქუთაისი', 239226);
INSERT INTO inventories (name, location, price) VALUES ('TS V-98', 'ხაშური', 60952);
INSERT INTO inventories (name, location, price) VALUES ('JS V-10', 'ხაშური', 90711);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-22', 'გორი', 190521);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-74', 'ხაშური', 14853);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-39', 'გორი', 140436);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-53', 'ხაშური', 41687);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-59', 'რუსთავი', 237238);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-88', 'თბილისი', 89360);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-53', 'ზუგდიდი', 44058);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-49', 'გორი', 225399);
INSERT INTO inventories (name, location, price) VALUES ('JS V-97', 'ბათუმი', 51851);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-90', 'ბათუმი', 4173);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-47', 'რუსთავი', 55723);
INSERT INTO inventories (name, location, price) VALUES ('TS V-93', 'ხაშური', 275549);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-40', 'ქუთაისი', 51773);
INSERT INTO inventories (name, location, price) VALUES ('TS V-68', 'რუსთავი', 230327);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-57', 'ქუთაისი', 101722);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-45', 'ქუთაისი', 218399);
INSERT INTO inventories (name, location, price) VALUES ('The Go Programming Language V-36', 'ბათუმი', 251149);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-15', 'ქუთაისი', 222760);
INSERT INTO inventories (name, location, price) VALUES ('JS V-78', 'რუსთავი', 182448);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-48', 'გორი', 104321);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-95', 'ბათუმი', 208655);
INSERT INTO inventories (name, location, price) VALUES ('Go Intro V-89', 'ზუგდიდი', 41956);
INSERT INTO inventories (name, location, price) VALUES ('TS V-65', 'რუსთავი', 16931);
INSERT INTO inventories (name, location, price) VALUES ('TS V-77', 'ხაშური', 115242);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-19', 'ქუთაისი', 249550);
INSERT INTO inventories (name, location, price) VALUES ('Python Intro V-23', 'გორი', 77011);
INSERT INTO inventories (name, location, price) VALUES ('TS V-85', 'ხაშური', 268541);
INSERT INTO inventories (name, location, price) VALUES ('Data Smart V-85', 'თბილისი', 121673);
COMMIT;